In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as stl
import re

# -----------------------------

from catboost import CatBoostRegressor
from catboost import CatBoostClassifier

In [83]:
data = pd.read_excel('car details v4.xlsx')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [133]:
# data.info()
# data.columns
# data.shape
# data.isnull().sum()
# data['Seller Type'].value_counts().isnull().sum()
# data['Seller Type'].value_counts()

In [84]:
data.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [98]:
data['Engine_Num'] = data['Engine'].str.extract(r'(\d+\.?\d*)').astype(float)
data['Max_Power_Num'] = data['Max Power'].str.extract(r'(\d+\.?\d*)').astype(float)
data['Max_Torque_Num'] = data['Max Torque'].str.extract(r'(\d+\.?\d*)').astype(float)

data['Power RPM'] = data['Max Power'].str.split('@').str[1]
data['Power RPM'] = data['Power RPM'].str.replace('rpm','')

data['Torque RPM'] = data['Max Torque'].str.split('@').str[1]
data['Torque RPM'] = data['Torque RPM'].str.replace('rpm','')

cols = ['Engine_Num', 'Max_Power_Num', 'Max_Torque_Num', 'Torque RPM', 'Power RPM']

for col in cols:
    data[col] = data[col].astype(str).str.strip()
    data[col] = pd.to_numeric(data[col], errors='coerce')

In [99]:
train = data[data['Engine_Num'].notna()]
test = data[data['Engine_Num'].isna()]

x_train = train[['Model','Fuel Type']]
y_train = train['Engine_Num']
x_test = test[['Model','Fuel Type']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model','Fuel Type'])
pred = model.predict(x_test)
data.loc[data['Engine_Num'].isna(),'Engine_Num']= pred

data['Engine_Num'] = data['Engine_Num'].astype(int)

# ------------------------------------------------------------

train = data[data['Max_Power_Num'].notna()]
test = data[data['Max_Power_Num'].isna()]

x_train = train[['Model','Fuel Type']]
y_train = train['Max_Power_Num']
x_test = test[['Model','Fuel Type']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model','Fuel Type'])
pred = model.predict(x_test)
data.loc[data['Max_Power_Num'].isna(),'Max_Power_Num']= pred

data['Max_Power_Num'] = data['Max_Power_Num'].astype(int)

# ------------------------------------------------------------

train = data[data['Max_Torque_Num'].notna()]
test = data[data['Max_Torque_Num'].isna()]

x_train = train[['Model','Fuel Type']]
y_train = train['Max_Torque_Num']
x_test = test[['Model','Fuel Type']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model','Fuel Type'])
pred = model.predict(x_test)
data.loc[data['Max_Torque_Num'].isna(),'Max_Torque_Num']= pred

data['Max_Torque_Num'] = data['Max_Torque_Num'].astype(int)

# ------------------------------------------------------------

train = data[data['Torque RPM'].notna()]
test = data[data['Torque RPM'].isna()]

x_train = train[['Model']]
y_train = train['Torque RPM']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Torque RPM'].isna(),'Torque RPM']= pred

# ------------------------------------------------------------

train = data[data['Power RPM'].notna()]
test = data[data['Power RPM'].isna()]

x_train = train[['Model']]
y_train = train['Power RPM']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Power RPM'].isna(),'Power RPM']= pred

In [100]:
train = data[data['Drivetrain'].notna()]
test = data[data['Drivetrain'].isna()]

x_train = train[['Model']]
y_train = train['Drivetrain']
x_test = test[['Model']]

model = CatBoostClassifier(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Drivetrain'].isna(),'Drivetrain']= pred

In [ ]:
train = data[data['Length'].notna()]
test = data[data['Length'].isna()]

x_train = train[['Model']]
y_train = train['Length']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Length'].isna(),'Length']= pred

data['Length'] = data['Length'].astype(int)

data['Length'] = data['Length'].astype(str) +' mm'

# ------------------------------------------------------------

train = data[data['Width'].notna()]
test = data[data['Width'].isna()]

x_train = train[['Model']]
y_train = train['Width']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Width'].isna(),'Width']= pred

data['Width'] = data['Width'].astype(int)

data['Width'] = data['Width'].astype(str) +' mm'

# ------------------------------------------------------------

train = data[data['Height'].notna()]
test = data[data['Height'].isna()]

x_train = train[['Model']]
y_train = train['Height']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Height'].isna(),'Height']= pred

data['Height'] = data['Height'].astype(int)

data['Height'] = data['Height'].astype(str) +' mm'

In [102]:
train = data[data['Seating Capacity'].notna()]
test = data[data['Seating Capacity'].isna()]

x_train = train[['Model']]
y_train = train['Seating Capacity']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Seating Capacity'].isna(),'Seating Capacity']= pred

data['Seating Capacity'] = data['Seating Capacity'].astype(int)

In [103]:
train = data[data['Fuel Tank Capacity'].notna()]
test = data[data['Fuel Tank Capacity'].isna()]

x_train = train[['Model']]
y_train = train['Fuel Tank Capacity']
x_test = test[['Model']]

model = CatBoostRegressor(verbose=False)
model.fit(x_train,y_train,cat_features=['Model'])
pred = model.predict(x_test)
data.loc[data['Fuel Tank Capacity'].isna(),'Fuel Tank Capacity']= pred

data['Fuel Tank Capacity'] = data['Fuel Tank Capacity'].astype(int)

data['Fuel Tank Capacity'] = data['Fuel Tank Capacity'].astype(str) +' L'

In [106]:
cols2 = ['Engine_Num', 'Max_Power_Num', 'Max_Torque_Num', 'Torque RPM', 'Power RPM']

for col2 in cols2:
    data[col2] = data[col2].astype(str).str.strip()
    data[col2] = pd.to_numeric(data[col2], errors='coerce').astype(int)

In [ ]:
data['Engine_Num'] = data['Engine_Num'].astype(str) +' cc'
data['Kilometer'] = data['Kilometer'].astype(str) +' km'
data['Max_Power_Num'] = data['Max_Power_Num'].astype(str) +' bhp @ ' + data['Torque RPM'].astype(str) + ' rpm'
data['Max_Torque_Num'] = data['Max_Torque_Num'].astype(str) +' Nm @ ' + data['Power RPM'].astype(str) + ' rpm'

In [ ]:
data = data.drop(columns=['Engine','Max Power','Max Torque','Power RPM','Torque RPM'])

data.rename(columns={'Engine_Num':'Engine'}, inplace = True)
data.rename(columns={'Max_Power_Num':'Max Power'}, inplace = True)
data.rename(columns={'Max_Torque_Num':'Max Torque'}, inplace = True)
data.rename(columns={'Kilometer': 'Kilometers Driven'}, inplace = True)
data.rename(columns={'Make':'Brand'}, inplace = True)

In [118]:
cl = data.pop('Engine_Num')
data.insert(11, 'Engine_Num', cl)

cl = data.pop('Max_Power_Num')
data.insert(12, 'Max_Power_Num', cl)

cl = data.pop('Max_Torque_Num')
data.insert(13, 'Max_Torque_Num', cl)

cl = data.pop('Fuel Tank Capacity')
data.insert(18, 'Fuel Tank Capacity', cl)

In [4]:
data2 = pd.read_excel('car_details_cleaned.xlsx')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [86]:
data2.head()

,Brand,Model,Price,Year,Kilometers Driven,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Power,Torque,Drivetrain,Length,Width,Height,Fuel Tank Capacity,Seating Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150 km,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990 mm,1680 mm,1505 mm,35 L,5
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000 km,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995 mm,1695 mm,1555 mm,42 L,5
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000 km,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112 Nm @ 4000 rpm,FWD,3585 mm,1595 mm,1550 mm,35 L,5
3,Toyota,Glanza G,799000,2019,37500 km,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995 mm,1745 mm,1510 mm,37 L,5
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000 km,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735 mm,1830 mm,1795 mm,55 L,7

In [ ]:
data2['Power_rpm'] = data2['Max Torque'].str.extract(r'(@\s*\d+\s*rpm)')[0]
data2['Torque_rpm'] = data2['Max Power'].str.extract(r'(@\s*\d+\s*rpm)')[0]

data2['Max Power'] = data2.apply(lambda row: row['Max Power'].replace(data2['Power_rpm'][row.name],data2['Torque_rpm'][row.name]), axis=1)
data2['Max Torque'] = data2.apply(lambda row: row['Max Torque'].replace(data2['Torque_rpm'][row.name],data2['Power_rpm'][row.name]), axis=1)

data2['Power_bhp'] = data2['Max Power'].str.extract(r'(\d+\s*bhp)')
data2['Torque_Nm'] = data2['Max Torque'].str.extract(r'(\d+\s*Nm)')

data2['Power'] = data2['Power_bhp']+[' ']+data2['Power_rpm']
data2['Torque'] = data2['Torque_Nm']+[' ']+data2['Torque_rpm']

data2 = data2.drop(columns=['Max Power','Max Torque','Power_rpm','Torque_rpm','Power_bhp','Torque_Nm'])

cl = data2.pop('Power')
data2.insert(12, 'Power', cl)

cl = data2.pop('Torque')
data2.insert(13, 'Torque', cl)

In [4]:
data2.to_excel('car_details_cleaned.xlsx', index=None)

In [6]:
models_list = [
    "5-Series 520d Sedan", "5-Series 525d Sedan", "Ecosport Titanium 1.5L TDCi",
    "Figo Duratorq Diesel Titanium 1.4", "Amaze 1.2 VX AT i-VTEC", "Brio E MT",
    "Brio S MT", "CR-V 2.4 AT", "City 1.5 S MT", "City 1.5 V AT", "City 1.5 V MT",
    "City ZX CVT Petrol", "City ZX Diesel", "Civic 1.8V MT", "Creta E Plus 1.6 Petrol",
    "Elite i20 Magna Executive 1.2", "Elite i20 Sportz 1.2", "i20 Active 1.2 SX",
    "i20 Asta 1.2", "i20 Magna 1.2", "i20 Sportz 1.4 CRDI", "Evoque HSE Dynamic",
    "TUV300 T10", "Alto LXi CNG", "Ritz Vdi BS-IV", "Swift DZire VXI", "Swift LXi",
    "Swift VDi", "Swift VXi", "Swift ZDi", "Swift ZXi", "CLA 200 CDI Sport",
    "GLA 200 Sport", "Corolla Altis 1.8 G", "Polo Comfortline 1.2L (P)",
    "Polo GT TSI", "Polo Highline1.2L (P)", "Vento Highline Petrol AT",
]

filtered = data2[data2["Model"].isin(models_list)].copy()

cols_to_fix = ["Engine", "Power", "Torque", "Length", "Width", "Height",
               "Fuel Tank Capacity", "Seating Capacity"]

filtered = filtered[["Model"] + cols_to_fix].copy()

for col in cols_to_fix:
    filtered[col] = filtered.groupby("Model")[col].transform(
        lambda x: x.mode().iloc[0]
    )

filtered = filtered.sort_values("Model")
filtered

,Model,Engine,Power,Torque,Length,Width,Height,Fuel Tank Capacity,Seating Capacity
334,5-Series 520d Sedan,1995 cc,184 bhp @ 4000 rpm,380 Nm @ 1750 rpm,4899 mm,2094 mm,1464 mm,62 L,5
180,5-Series 520d Sedan,1995 cc,184 bhp @ 4000 rpm,380 Nm @ 1750 rpm,4899 mm,2094 mm,1464 mm,62 L,5
134,5-Series 520d Sedan,1995 cc,184 bhp @ 4000 rpm,380 Nm @ 1750 rpm,4899 mm,2094 mm,1464 mm,62 L,5
900,5-Series 520d Sedan,1995 cc,184 bhp @ 4000 rpm,380 Nm @ 1750 rpm,4899 mm,2094 mm,1464 mm,62 L,5
868,5-Series 525d Sedan,1995 cc,217 bhp @ 4400 rpm,450 Nm @ 1500 rpm,4899 mm,2094 mm,1464 mm,62 L,5
276,5-Series 525d Sedan,1995 cc,217 bhp @ 4400 rpm,450 Nm @ 1500 rpm,4899 mm,2094 mm,1464 mm,62 L,5
1449,5-Series 525d Sedan,1995 cc,217 bhp @ 4400 rpm,450 Nm @ 1500 rpm,4899 mm,2094 mm,1464 mm,62 L,5
1505,Alto LXi CNG,796 cc,39 bhp @ 6200 rpm,54 Nm @ 3000 rpm,3495 mm,1475 mm,1460 mm,35 L,5
24,Alto LXi CNG,796 cc,39 bhp @ 6200 rpm,54 Nm @ 3000 rpm,3495 mm,1475 mm,1460 mm,35 L,5
1038,Alto LXi CNG,796 cc,39 bhp @ 6200 rpm,54 Nm @ 3000 rpm,3495 mm,1475 mm,1460 mm,35 L,5
376,Amaze 1.2 VX AT i-VTEC,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3990 mm,1680 mm,1505 mm,35 L,5
1569,Amaze 1.2 VX AT i-VTEC,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3990 mm,1680 mm,1505 mm,35 L,5
722,Brio E MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1483 mm,35 L,4
792,Brio E MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1483 mm,35 L,4
1960,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
332,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
694,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
488,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
59,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
108,Brio S MT,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,3610 mm,1680 mm,1500 mm,35 L,5
453,CLA 200 CDI Sport,2143 cc,134 bhp @ 3600 rpm,300 Nm @ 1600 rpm,4630 mm,1777 mm,1432 mm,56 L,5
1269,CLA 200 CDI Sport,2143 cc,134 bhp @ 3600 rpm,300 Nm @ 1600 rpm,4630 mm,1777 mm,1432 mm,56 L,5
164,CR-V 2.4 AT,2357 cc,190 bhp @ 5832 rpm,334 Nm @ 3562 rpm,4637 mm,1860 mm,1704 mm,62 L,4
1527,CR-V 2.4 AT,2357 cc,190 bhp @ 5832 rpm,334 Nm @ 3562 rpm,4637 mm,1860 mm,1704 mm,62 L,4
33,CR-V 2.4 AT,2357 cc,190 bhp @ 5832 rpm,334 Nm @ 3562 rpm,4637 mm,1860 mm,1704 mm,62 L,4
2002,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
330,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
220,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1102,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
381,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1585,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1733,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
110,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
547,City 1.5 S MT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1022,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
959,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
892,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1012,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1468,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
1469,City 1.5 V AT,1497 cc,118 bhp @ 6600 rpm,146 Nm @ 4600 rpm,4420 mm,1695 mm,1480 mm,42 L,5
627,City 1.5 V MT,1497 cc,116 bhp @ 6600 rpm,146 Nm @ 4800 rpm,4440 mm,1695 mm,1485 mm,42 L,5
1857,City 1.5 V MT,1497 cc,116 bhp @ 6600 rpm,146 Nm @ 4800 rpm,4440 mm,1695 mm,1485 mm,42 L,5
1556,City 1.5 V MT,1497 cc,116 bhp @ 6600 rpm,146 Nm @ 4800 rpm,4440 mm,1695 mm,1485 mm,42 L,5
663,City 1.5 V MT,1497 cc,116 bhp @ 6600 rpm,146 Nm @ 4800 rpm,4440 mm,1695 mm,1485 mm,42 L,5
1492,City 1.5 V MT,1497 cc,116 bhp @ 6600 rpm,146 Nm @ 4800 rpm,4440 mm,1695 mm,1485 mm,42 L,5
362,City ZX CVT Petrol,1498 cc,119 bhp @ 6600 rpm,145 Nm @ 4300 rpm,4549 mm,1748 mm,1489 mm,40 L,5
969,City ZX CVT Petrol,1498 cc,119 bhp @ 6600 rpm,145 Nm @ 4300 rpm,4549 mm,1748 mm,1489 mm,40 L,5
420,City ZX CVT Petrol,1498 cc,119 bhp @ 6600 rpm,145 Nm @ 4300 rpm,4549 mm,1748 mm,1489 mm,40 L,5
769,City ZX Diesel,1498 cc,98 bhp @ 3600 rpm,200 Nm @ 1750 rpm,4440 mm,1695 mm,1489 mm,40 L,5
1548,City ZX Diesel,1498 cc,98 bhp @ 3600 rpm,200 Nm @ 1750 rpm,4440 mm,1695 mm,1489 mm,40 L,5
1396,Civic 1.8V MT,1799 cc,130 bhp @ 6300 rpm,134 Nm @ 3562 rpm,4545 mm,1686 mm,1450 mm,50 L,4
1095,Civic 1.8V MT,1799 cc,130 bhp @ 6300 rpm,134 Nm @ 3562 rpm,4545 mm,1686 mm,1450 mm,50 L,4
1152,Corolla Altis 1.8 G,1794 cc,132 bhp @ 6000 rpm,170 Nm @ 4200 rpm,4540 mm,1760 mm,1480 mm,55 L,5
1263,Corolla Altis 1.8 G,1794 cc,132 bhp @ 6000 rpm,170 Nm @ 4200 rpm,4540 mm,1760 mm,1480 mm,55 L,5
1818,Corolla Altis 1.8 G,1794 cc,132 bhp @ 6000 rpm,170 Nm @ 4200 rpm,4540 mm,1760 mm,1480 mm,55 L,5
100,Corolla Altis 1.8 G,1794 cc,132 bhp @ 6000 rpm,170 Nm @ 4200 rpm,4540 mm,1760 mm,1480 mm,55 L,5
346,Corolla Altis 1.8 G,1794 cc,132 bhp @ 6000 rpm,170 Nm @ 4200 rpm,4540 mm,1760 mm,1480 mm,55 L,5
1183,Creta E Plus 1.6 Petrol,1591 cc,122 bhp @ 6400 rpm,154 Nm @ 4850 rpm,4270 mm,1780 mm,1630 mm,60 L,5
1218,Creta E Plus 1.6 Petrol,1591 cc,122 bhp @ 6400 rpm,154 Nm @ 4850 rpm,4270 mm,1780 mm,1630 mm,60 L,5
1450,Creta E Plus 1.6 Petrol,1591 cc,122 bhp @ 6400 rpm,154 Nm @ 4850 rpm,4270 mm,1780 mm,1630 mm,60 L,5
1347,Ecosport Titanium 1.5L TDCi,1498 cc,99 bhp @ 3750 rpm,205 Nm @ 1750 rpm,3998 mm,1765 mm,1647 mm,52 L,5
451,Ecosport Titanium 1.5L TDCi,1498 cc,99 bhp @ 3750 rpm,205 Nm @ 1750 rpm,3998 mm,1765 mm,1647 mm,52 L,5
1976,Ecosport Titanium 1.5L TDCi,1498 cc,99 bhp @ 3750 rpm,205 Nm @ 1750 rpm,3998 mm,1765 mm,1647 mm,52 L,5
1654,Elite i20 Magna Executive 1.2,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3985 mm,1734 mm,1505 mm,40 L,5
849,Elite i20 Magna Executive 1.2,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3985 mm,1734 mm,1505 mm,40 L,5
882,Elite i20 Sportz 1.2,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3985 mm,1734 mm,1505 mm,40 L,5
10,Elite i20 Sportz 1.2,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3985 mm,1734 mm,1505 mm,40 L,5
1143,Evoque HSE Dynamic,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,4360 mm,2120 mm,1635 mm,57 L,5
443,Evoque HSE Dynamic,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,4360 mm,2120 mm,1635 mm,57 L,5
318,Evoque HSE Dynamic,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,4360 mm,2120 mm,1635 mm,57 L,5
1279,Figo Duratorq Diesel Titanium 1.4,1399 cc,68 bhp @ 4000 rpm,160 Nm @ 2000 rpm,3795 mm,1680 mm,1427 mm,45 L,5
74,Figo Duratorq Diesel Titanium 1.4,1399 cc,68 bhp @ 4000 rpm,160 Nm @ 2000 rpm,3795 mm,1680 mm,1427 mm,45 L,5
1501,GLA 200 Sport,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,4424 mm,1804 mm,1494 mm,50 L,5
1426,GLA 200 Sport,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,4424 mm,1804 mm,1494 mm,50 L,5
951,GLA 200 Sport,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,4424 mm,1804 mm,1494 mm,50 L,5
1570,Polo Comfortline 1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
290,Polo Comfortline 1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
1129,Polo Comfortline 1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
1106,Polo Comfortline 1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
578,Polo GT TSI,1197 cc,103 bhp @ 5000 rpm,175 Nm @ 1500 rpm,3971 mm,1682 mm,1469 mm,45 L,5
280,Polo GT TSI,1197 cc,103 bhp @ 5000 rpm,175 Nm @ 1500 rpm,3971 mm,1682 mm,1469 mm,45 L,5
321,Polo GT TSI,1197 cc,103 bhp @ 5000 rpm,175 Nm @ 1500 rpm,3971 mm,1682 mm,1469 mm,45 L,5
14,Polo GT TSI,1197 cc,103 bhp @ 5000 rpm,175 Nm @ 1500 rpm,3971 mm,1682 mm,1469 mm,45 L,5
812,Polo Highline1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
1536,Polo Highline1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
1320,Polo Highline1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
76,Polo Highline1.2L (P),1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,3970 mm,1682 mm,1453 mm,45 L,5
1648,Ritz Vdi BS-IV,1248 cc,75 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3715 mm,1680 mm,1620 mm,43 L,5
1037,Ritz Vdi BS-IV,1248 cc,75 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3715 mm,1680 mm,1620 mm,43 L,5
532,Ritz Vdi BS-IV,1248 cc,75 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3715 mm,1680 mm,1620 mm,43 L,5
225,Ritz Vdi BS-IV,1248 cc,75 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3715 mm,1680 mm,1620 mm,43 L,5
439,Ritz Vdi BS-IV,1248 cc,75 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3715 mm,1680 mm,1620 mm,43 L,5
1251,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
2005,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
124,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
269,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
1118,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
602,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
210,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
1739,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
647,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
1759,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
141,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
1410,Swift DZire VXI,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3995 mm,1695 mm,1555 mm,42 L,5
1242,Swift LXi,1197 cc,83 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1414,Swift LXi,1197 cc,83 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1363,Swift LXi,1197 cc,83 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
825,Swift LXi,1197 cc,83 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1165,Swift LXi,1197 cc,83 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1475,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
328,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1772,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
883,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
493,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1273,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
2013,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
706,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1123,Swift VDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
945,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1965,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1962,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
989,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1005,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1773,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
601,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1702,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1546,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1346,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
325,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
564,Swift VXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
190,Swift ZDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3840 mm,1695 mm,1530 mm,37 L,5
227,Swift ZDi,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,3840 mm,1695 mm,1530 mm,37 L,5
1684,Swift ZXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
500,Swift ZXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1760,Swift ZXi,1197 cc,85 bhp @ 6000 rpm,114 Nm @ 4000 rpm,3850 mm,1695 mm,1530 mm,42 L,5
1304,TUV300 T10,1493 cc,100 bhp @ 3750 rpm,240 Nm @ 1600 rpm,3995 mm,1795 mm,1817 mm,60 L,7
1299,TUV300 T10,1493 cc,100 bhp @ 3750 rpm,240 Nm @ 1600 rpm,3995 mm,1795 mm,1817 mm,60 L,7
571,Vento Highline Petrol AT,1598 cc,103 bhp @ 5250 rpm,134 Nm @ 3562 rpm,4384 mm,1686 mm,1466 mm,55 L,4
2003,Vento Highline Petrol AT,1598 cc,103 bhp @ 5250 rpm,134 Nm @ 3562 rpm,4384 mm,1686 mm,1466 mm,55 L,4
1707,i20 Active 1.2 SX,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3995 mm,1760 mm,1555 mm,45 L,5
798,i20 Active 1.2 SX,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3995 mm,1760 mm,1555 mm,45 L,5
1094,i20 Active 1.2 SX,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,3995 mm,1760 mm,1555 mm,45 L,5
1074,i20 Asta 1.2,1197 cc,80 bhp @ 5200 rpm,112 Nm @ 4000 rpm,3940 mm,1686 mm,1483 mm,40 L,4
1078,i20 Asta 1.2,1197 cc,80 bhp @ 5200 rpm,112 Nm @ 4000 rpm,3940 mm,1686 mm,1483 mm,40 L,4
146,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
1703,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
1903,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
1442,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
814,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
1184,i20 Magna 1.2,1190 cc,77 bhp @ 5896 rpm,113 Nm @ 4000 rpm,3912 mm,1666 mm,1483 mm,39 L,4
1205,i20 Sportz 1.4 CRDI,1396 cc,90 bhp @ 4000 rpm,220 Nm @ 1750 rpm,3940 mm,1710 mm,1505 mm,45 L,5
817,i20 Sportz 1.4 CRDI,1396 cc,90 bhp @ 4000 rpm,220 Nm @ 1750 rpm,3940 mm,1710 mm,1505 mm,45 L,5
2052,i20 Sportz 1.4 CRDI,1396 cc,90 bhp @ 4000 rpm,220 Nm @ 1750 rpm,3940 mm,1710 mm,1505 mm,45 L,5

In [ ]:
def fix_and_filter(input_path="car_details_cleaned.xlsx",
                    output_path="car_details_fixed.xlsx"):

    data2 = pd.read_excel(input_path)

    cols_to_fix = ["Engine", "Power", "Torque", "Length", "Width", "Height",
                   "Fuel Tank Capacity", "Seating Capacity"]

    for col in cols_to_fix:
        data2[col] = data2.groupby("Model")[col].transform(
            lambda x: x.mode().iloc[0]
        )

    data2.to_excel(output_path, index=False)
    print(f"saved{output_path}")

    models_list = [
        "5-Series 520d Sedan", "5-Series 525d Sedan", "Ecosport Titanium 1.5L TDCi",
        "Figo Duratorq Diesel Titanium 1.4", "Amaze 1.2 VX AT i-VTEC", "Brio E MT",
        "Brio S MT", "CR-V 2.4 AT", "City 1.5 S MT", "City 1.5 V AT", "City 1.5 V MT",
        "City ZX CVT Petrol", "City ZX Diesel", "Civic 1.8V MT", "Creta E Plus 1.6 Petrol",
        "Elite i20 Magna Executive 1.2", "Elite i20 Sportz 1.2", "i20 Active 1.2 SX",
        "i20 Asta 1.2", "i20 Magna 1.2", "i20 Sportz 1.4 CRDI", "Evoque HSE Dynamic",
        "TUV300 T10", "Alto LXi CNG", "Ritz Vdi BS-IV", "Swift DZire VXI", "Swift LXi",
        "Swift VDi", "Swift VXi", "Swift ZDi", "Swift ZXi", "CLA 200 CDI Sport",
        "GLA 200 Sport", "Corolla Altis 1.8 G", "Polo Comfortline 1.2L (P)",
        "Polo GT TSI", "Polo Highline1.2L (P)", "Vento Highline Petrol AT",
    ]

    filtered = data2[data2["Model"].isin(models_list)].copy()
    filtered = filtered[["Model"] + cols_to_fix].copy()
    filtered = filtered.sort_values("Model")

    return data2, filtered


data2, filtered = fix_and_filter()
filtered

In [ ]:
data2['Fuel Type'] = data2['Fuel Type'].replace('CNG + CNG', 'CNG')
data2['Owner'] = data2['Owner'].replace('4 or More', 'More Than 4')

In [10]:
data2.to_excel('car_details_fixed.xlsx', index=False)